sources:
- name: member_ds.html
  url: https://www.cpf.gov.sg/member/ds.html
  type: html
  source: CPF
- name: member_ds_account_settings
  url: https://www.cpf.gov.sg/member/ds/account-settings
  type: html
  source: CPF
- name: member_logout
  url: https://www.cpf.gov.sg/member/logout
  type: html
  source: CPF
- name: member_who_we_are
  url: https://www.cpf.gov.sg/member/who-we-are
  type: html
  source: CPF
- name: member_tools_and_services
  url: https://www.cpf.gov.sg/member/tools-and-services
  type: html
  source: CPF
- name: member_infohub
  url: https://www.cpf.gov.sg/member/infohub
  type: html
  source: CPF
- name: member_home_ownership
  url: https://www.cpf.gov.sg/member/home-ownership
  type: html
  source: CPF
- name: member_cpf_overview
  url: https://www.cpf.gov.sg/member/cpf-overview
  type: html
  source: CPF
- name: member_plan_with_cpf
  url: https://www.cpf.gov.sg/member/plan-with-cpf
  type: html
  source: CPF
- name: member_tools_and_services_calculators
  url: https://www.cpf.gov.sg/member/tools-and-services/calculators
  type: html
  source: CPF
- name: member_tools_and_services_forms_e_applications
  url: https://www.cpf.gov.sg/member/tools-and-services/forms-e-applications
  type: html
  source: CPF
- name: member_ds
  url: https://www.cpf.gov.sg/member/ds
  type: html
  source: CPF
- name: member_ds_plan_with_cpf
  url: https://www.cpf.gov.sg/member/ds/plan-with-cpf
  type: html
  source: CPF
- name: member_ds_activities
  url: https://www.cpf.gov.sg/member/ds/activities
  type: html
  source: CPF
- name: member_ds_dashboards_retirement
  url: https://www.cpf.gov.sg/member/ds/dashboards/retirement
  type: html
  source: CPF
- name: member_ds_dashboards_home_ownership
  url: https://www.cpf.gov.sg/member/ds/dashboards/home-ownership
  type: html
  source: CPF
- name: member_ds_dashboards_healthcare
  url: https://www.cpf.gov.sg/member/ds/dashboards/healthcare
  type: html
  source: CPF
- name: member_ds_dashboards_providing_for_your_loved_ones
  url: https://www.cpf.gov.sg/member/ds/dashboards/providing-for-your-loved-ones
  type: html
  source: CPF
- name: member_ds_dashboards_self_employment
  url: https://www.cpf.gov.sg/member/ds/dashboards/self-employment
  type: html
  source: CPF
- name: member_ds_dashboards_investment
  url: https://www.cpf.gov.sg/member/ds/dashboards/investment
  type: html
  source: CPF
- name: member_ds_dashboards_education
  url: https://www.cpf.gov.sg/member/ds/dashboards/education
  type: html
  source: CPF
- name: member_ds_dashboards_child
  url: https://www.cpf.gov.sg/member/ds/dashboards/child
  type: html
  source: CPF
- name: member_ds_statements_transaction_history
  url: https://www.cpf.gov.sg/member/ds/statements/transaction-history
  type: html
  source: CPF
- name: member_ds_statements_yearly_statement_of_account
  url: https://www.cpf.gov.sg/member/ds/statements/yearly-statement-of-account
  type: html
  source: CPF
- name: member_growing_your_savings
  url: https://www.cpf.gov.sg/member/growing-your-savings
  type: html
  source: CPF
- name: member_growing_your_savings_cpf_contributions_saving_as_an_employee
  url: https://www.cpf.gov.sg/member/growing-your-savings/cpf-contributions/saving-as-an-employee
  type: html
  source: CPF
- name: member_growing_your_savings_cpf_contributions_saving_as_a_self_employed_person
  url: https://www.cpf.gov.sg/member/growing-your-savings/cpf-contributions/saving-as-a-self-employed-person
  type: html
  source: CPF
- name: member_growing_your_savings_cpf_contributions_saving_as_a_platform_worker
  url: https://www.cpf.gov.sg/member/growing-your-savings/cpf-contributions/saving-as-a-platform-worker
  type: html
  source: CPF
- name: member_growing_your_savings_saving_more_with_cpf_top_up_to_enjoy_higher_retirement_payouts
  url: https://www.cpf.gov.sg/member/growing-your-savings/saving-more-with-cpf/top-up-to-enjoy-higher-retirement-payouts
  type: html
  source: CPF
- name: member_growing_your_savings_saving_more_with_cpf_top_up_your_medisave_savings
  url: https://www.cpf.gov.sg/member/growing-your-savings/saving-more-with-cpf/top-up-your-medisave-savings
  type: html
  source: CPF
- name: member_growing_your_savings_saving_more_with_cpf_make_a_voluntary_housing_refund
  url: https://www.cpf.gov.sg/member/growing-your-savings/saving-more-with-cpf/make-a-voluntary-housing-refund
  type: html
  source: CPF
- name: member_growing_your_savings_saving_more_with_cpf_top_up_ordinary_special_and_medisave_savings
  url: https://www.cpf.gov.sg/member/growing-your-savings/saving-more-with-cpf/top-up-ordinary-special-and-medisave-savings
  type: html
  source: CPF
- name: member_growing_your_savings_earning_higher_returns_investing_your_cpf_savings
  url: https://www.cpf.gov.sg/member/growing-your-savings/earning-higher-returns/investing-your-cpf-savings
  type: html
  source: CPF
- name: member_growing_your_savings_earning_higher_returns_earning_attractive_interest
  url: https://www.cpf.gov.sg/member/growing-your-savings/earning-higher-returns/earning-attractive-interest
  type: html
  source: CPF
- name: member_growing_your_savings_government_support_matching_grant_for_retirement
  url: https://www.cpf.gov.sg/member/growing-your-savings/government-support/matching-grant-for-retirement
  type: html
  source: CPF
- name: member_growing_your_savings_government_support_medisave_matching
  url: https://www.cpf.gov.sg/member/growing-your-savings/government-support/medisave-matching
  type: html
  source: CPF
- name: member_growing_your_savings_government_support_workfare_income_supplement
  url: https://www.cpf.gov.sg/member/growing-your-savings/government-support/workfare-income-supplement
  type: html
  source: CPF
- name: member_growing_your_savings_government_support_platform_workers_cpf_transition_support
  url: https://www.cpf.gov.sg/member/growing-your-savings/government-support/platform-workers-cpf-transition-support
  type: html
  source: CPF
- name: member_retirement_income
  url: https://www.cpf.gov.sg/member/retirement-income
  type: html
  source: CPF
- name: member_retirement_income_milestones_reaching_age_55
  url: https://www.cpf.gov.sg/member/retirement-income/milestones/reaching-age-55
  type: html
  source: CPF
- name: member_retirement_income_milestones_reaching_age_65
  url: https://www.cpf.gov.sg/member/retirement-income/milestones/reaching-age-65
  type: html
  source: CPF
- name: member_retirement_income_about_cpf_planner_retirement_income
  url: https://www.cpf.gov.sg/member/retirement-income/about-cpf-planner-retirement-income
  type: html
  source: CPF
- name: member_retirement_income_monthly_payouts_cpf_life
  url: https://www.cpf.gov.sg/member/retirement-income/monthly-payouts/cpf-life
  type: html
  source: CPF
- name: member_retirement_income_monthly_payouts_non_cpf_life
  url: https://www.cpf.gov.sg/member/retirement-income/monthly-payouts/non-cpf-life
  type: html
  source: CPF
- name: member_retirement_income_retirement_withdrawals_withdrawing_for_immediate_retirement_needs
  url: https://www.cpf.gov.sg/member/retirement-income/retirement-withdrawals/withdrawing-for-immediate-retirement-needs
  type: html
  source: CPF
- name: member_retirement_income_retirement_withdrawals_withdrawing_on_reduced_life_expectancy
  url: https://www.cpf.gov.sg/member/retirement-income/retirement-withdrawals/withdrawing-on-reduced-life-expectancy
  type: html
  source: CPF
- name: member_retirement_income_government_support_silver_support_scheme
  url: https://www.cpf.gov.sg/member/retirement-income/government-support/silver-support-scheme
  type: html
  source: CPF
- name: member_home_ownership_using_your_cpf_to_buy_a_home
  url: https://www.cpf.gov.sg/member/home-ownership/using-your-cpf-to-buy-a-home
  type: html
  source: CPF
- name: member_home_ownership_protecting_against_losing_your_home
  url: https://www.cpf.gov.sg/member/home-ownership/protecting-against-losing-your-home
  type: html
  source: CPF
- name: member_home_ownership_home_purchase_planner
  url: https://www.cpf.gov.sg/member/home-ownership/home-purchase-planner
  type: html
  source: CPF
- name: member_home_ownership_home_buying_guide_for_members_below_55
  url: https://www.cpf.gov.sg/member/home-ownership/home-buying-guide-for-members-below-55
  type: html
  source: CPF
- name: member_home_ownership_home_buying_guide_for_members_above_55
  url: https://www.cpf.gov.sg/member/home-ownership/home-buying-guide-for-members-above-55
  type: html
  source: CPF
- name: member_healthcare_financing
  url: https://www.cpf.gov.sg/member/healthcare-financing
  type: html
  source: CPF
- name: member_healthcare_financing_using_your_medisave_savings
  url: https://www.cpf.gov.sg/member/healthcare-financing/using-your-medisave-savings
  type: html
  source: CPF
- name: member_healthcare_financing_medishield_life
  url: https://www.cpf.gov.sg/member/healthcare-financing/medishield-life
  type: html
  source: CPF
- name: member_healthcare_financing_getting_supplementary_coverage
  url: https://www.cpf.gov.sg/member/healthcare-financing/getting-supplementary-coverage
  type: html
  source: CPF
- name: member_healthcare_financing_eldershield
  url: https://www.cpf.gov.sg/member/healthcare-financing/eldershield
  type: html
  source: CPF
- name: member_healthcare_financing_careshield_life
  url: https://www.cpf.gov.sg/member/healthcare-financing/careshield-life
  type: html
  source: CPF
- name: member_healthcare_financing_health_insurance_planner
  url: https://www.cpf.gov.sg/member/healthcare-financing/health-insurance-planner
  type: html
  source: CPF
- name: member_account_services
  url: https://www.cpf.gov.sg/member/account-services
  type: html
  source: CPF
- name: member_ds
  url: https://www.cpf.gov.sg/member/ds/
  type: html
  source: CPF
- name: member_account_services_providing_for_your_loved_ones_making_a_cpf_nomination
  url: https://www.cpf.gov.sg/member/account-services/providing-for-your-loved-ones/making-a-cpf-nomination
  type: html
  source: CPF
- name: member_account_services_providing_for_your_loved_ones_insuring_to_protect_your_dependants
  url: https://www.cpf.gov.sg/member/account-services/providing-for-your-loved-ones/insuring-to-protect-your-dependants
  type: html
  source: CPF
- name: member_account_services_fighting_scams_cpf_account_safeguards
  url: https://www.cpf.gov.sg/member/account-services/fighting-scams/cpf-account-safeguards
  type: html
  source: CPF
- name: member_account_services_fighting_scams_trusted_contacts
  url: https://www.cpf.gov.sg/member/account-services/fighting-scams/trusted-contacts
  type: html
  source: CPF
- name: member_account_services_cpf_asset_management_on_your_passing_away
  url: https://www.cpf.gov.sg/member/account-services/cpf-asset-management/on-your-passing-away
  type: html
  source: CPF
- name: member_account_services_cpf_asset_management_on_leaving_singapore
  url: https://www.cpf.gov.sg/member/account-services/cpf-asset-management/on-leaving-singapore
  type: html
  source: CPF
- name: member_account_services_cpf_asset_management_on_divorce
  url: https://www.cpf.gov.sg/member/account-services/cpf-asset-management/on-divorce
  type: html
  source: CPF
- name: member_tools_and_services_calculators_cpf_housing_usage
  url: https://www.cpf.gov.sg/member/tools-and-services/calculators/cpf-housing-usage
  type: html
  source: CPF
- name: member_infohub_educational_resources_handy_cpf_calculators_and_resources_for_housing_planning
  url: https://www.cpf.gov.sg/member/infohub/educational-resources/handy-cpf-calculators-and-resources-for-housing-planning
  type: html
  source: CPF
- name: member_infohub_educational_resources_boost_your_retirement_by_monetising_your_flat
  url: https://www.cpf.gov.sg/member/infohub/educational-resources/boost-your-retirement-by-monetising-your-flat
  type: html
  source: CPF
- name: member_infohub_educational_resources_housing_planning_checklist_for_parents_of_all_life_stages
  url: https://www.cpf.gov.sg/member/infohub/educational-resources/housing-planning-checklist-for-parents-of-all-life-stages
  type: html
  source: CPF
- name: member_infohub_educational_resources
  url: https://www.cpf.gov.sg/member/infohub/educational-resources
  type: html
  source: CPF
- name: member_useful_links
  url: https://www.cpf.gov.sg/member/useful-links
  type: html
  source: CPF
- name: member_who_we_are_careers
  url: https://www.cpf.gov.sg/member/who-we-are/careers
  type: html
  source: CPF
- name: member_privacy_statement
  url: https://www.cpf.gov.sg/member/privacy-statement
  type: html
  source: CPF
- name: member_terms_of_use
  url: https://www.cpf.gov.sg/member/terms-of-use
  type: html
  source: CPF
- name: member_sitemap
  url: https://www.cpf.gov.sg/member/sitemap
  type: html
  source: CPF
- name: member_security_best_practices
  url: https://www.cpf.gov.sg/member/security-best-practices
  type: html
  source: CPF
- name: taxes_property_tax
  url: https://www.iras.gov.sg/taxes/property-tax
  type: html
  source: IRAS
- name: taxes_property_tax_property_owners
  url: https://www.iras.gov.sg/taxes/property-tax/property-owners
  type: html
  source: IRAS
- name: taxes_property_tax_property_owners_2026_property_tax_bill
  url: https://www.iras.gov.sg/taxes/property-tax/property-owners/2026-property-tax-bill
  type: html
  source: IRAS
- name: taxes_property_tax_property_owners_property_tax_at_a_glance
  url: https://www.iras.gov.sg/taxes/property-tax/property-owners/property-tax-at-a-glance
  type: html
  source: IRAS
- name: taxes_property_tax_property_owners_annual_value
  url: https://www.iras.gov.sg/taxes/property-tax/property-owners/annual-value
  type: html
  source: IRAS
- name: taxes_property_tax_property_owners_property_tax_rates
  url: https://www.iras.gov.sg/taxes/property-tax/property-owners/property-tax-rates
  type: html
  source: IRAS
- name: taxes_property_tax_property_owners_information_for_hdb_flat_owners
  url: https://www.iras.gov.sg/taxes/property-tax/property-owners/information-for-hdb-flat-owners
  type: html
  source: IRAS
- name: taxes_property_tax_property_owners_tax_bills_and_notices
  url: https://www.iras.gov.sg/taxes/property-tax/property-owners/tax-bills-and-notices
  type: html
  source: IRAS
- name: taxes_property_tax_property_owners_view_statement_of_account_or_view_bills_and_notices
  url: https://www.iras.gov.sg/taxes/property-tax/property-owners/view-statement-of-account-or-view-bills-and-notices
  type: html
  source: IRAS
- name: taxes_property_tax_property_owners_payments
  url: https://www.iras.gov.sg/taxes/property-tax/property-owners/payments
  type: html
  source: IRAS
- name: taxes_property_tax_property_owners_object_to_annual_value
  url: https://www.iras.gov.sg/taxes/property-tax/property-owners/object-to-annual-value
  type: html
  source: IRAS
- name: taxes_property_tax_property_owners_property_tax_reliefs
  url: https://www.iras.gov.sg/taxes/property-tax/property-owners/property-tax-reliefs
  type: html
  source: IRAS
- name: taxes_property_tax_property_owners_your_situation
  url: https://www.iras.gov.sg/taxes/property-tax/property-owners/your-situation
  type: html
  source: IRAS
- name: taxes_property_tax_property_buyers
  url: https://www.iras.gov.sg/taxes/property-tax/property-buyers
  type: html
  source: IRAS
- name: taxes_property_tax_property_buyers_buying_hdb_flats
  url: https://www.iras.gov.sg/taxes/property-tax/property-buyers/buying-hdb-flats
  type: html
  source: IRAS
- name: taxes_property_tax_property_buyers_buying_private_residential_properties
  url: https://www.iras.gov.sg/taxes/property-tax/property-buyers/buying-private-residential-properties
  type: html
  source: IRAS
- name: taxes_property_tax_property_buyers_buying_vacant_land_or_development_sites
  url: https://www.iras.gov.sg/taxes/property-tax/property-buyers/buying-vacant-land-or-development-sites
  type: html
  source: IRAS
- name: taxes_property_tax_property_buyers_buying_other_types_of_properties
  url: https://www.iras.gov.sg/taxes/property-tax/property-buyers/buying-other-types-of-properties
  type: html
  source: IRAS
- name: taxes_property_tax_property_professionals
  url: https://www.iras.gov.sg/taxes/property-tax/property-professionals
  type: html
  source: IRAS
- name: taxes_property_tax_property_professionals_real_estate_housing_agents
  url: https://www.iras.gov.sg/taxes/property-tax/property-professionals/real-estate-housing-agents
  type: html
  source: IRAS
- name: taxes_property_tax_property_professionals_appraisers_valuer
  url: https://www.iras.gov.sg/taxes/property-tax/property-professionals/appraisers-valuer
  type: html
  source: IRAS
